package by.htp.ex.controller;

public enum CommandName {
	GO_TO_BASE_PAGE, GO_TO_LOGINATION_PAGE, GO_TO_REGISTRATION_PAGE, GO_TO_NEWS_LIST, GO_TO_VIEW_NEWS, GO_TO_ERROR_PAGE,
	GO_TO_LATEST_NEWS_LIST, GO_TO_ADD_NEWS_PAGE, GO_TO_EDIT_NEWS,

	DO_SIGN_IN, DO_SIGN_OUT, DO_REGISTRATION, DO_ADD_NEWS, DO_EDIT_NEWS, DO_DELETE_NEWS,DO_CHANGE_LOCALE
}
